### ISSUE TITLE
Load adjustment not changing results

### ISSUE THREAD

**Issue by ewhite58** [NREL/REopt-API-Analysis#100]
### Discussed in https://github.com/NREL/REopt-API-Analysis/discussions/99

<div type='discussions-op-text'>

<sup>Originally posted by **ewhite58** February 15, 2023</sup>
Every time I adjust the load (increase to 115% or 150%) in the load profile section of a run in REopt, it doesn't change the results (cost, sizing of PVs/batteries). I can't find anything in the user manual that reflects the newer version of REopt - can anyone help? </div>

**Comment by ewhite58** [comment]
I figured it out - whatever you upload as your custom load profile is seen as the adjusted load by the tool. For example, say the load I’m inputting is 100 kWh. If I change the load adjustment in the tool to 75%, then the original load would be 133.3 kWh, and adjusted would be 100 kWh. If I change the load adjustment in the tool to 125%, then the original load would be 80 kWh, and adjusted would be 100 kWh.

**Comment by adfarth** [comment]
> I figured it out - whatever you upload as your custom load profile is seen as the adjusted load by the tool. For example, say the load I’m inputting is 100 kWh. If I change the load adjustment in the tool to 75%, then the original load would be 133.3 kWh, and adjusted would be 100 kWh. If I change the load adjustment in the tool to 125%, then the original load would be 80 kWh, and adjusted would be 100 kWh.

Hello, apologies for the delayed response. Our UI developers have discovered a bug with the custom load profiles and the load adjustment slider. The bug occurs when the profile is uploaded, and then the slider is adjusted (as opposed to vice versa). We are now working to address this and will update here when the fix is complete. Thank you very much for drawing our attention to this and apologies for the inconvenience!

**Comment by adfarth** [comment]
Hello, we have identified and now fixed a bug in the web tool in which the load adjustment slider bar was incorrectly adjusting a custom load profile. The slider bar should now work as expected (multiply the custom load in each timestep by XXX%). Apologies for the inconvenience and thank you for bringing this to our attention!

**Comment by ewhite58** [comment]
Hello,

Thank you so much for looking into this, and for fixing the tool!
