### ISSUE TITLE
Grid Charging Battery Profile

### ISSUE THREAD

**Issue by tingm417** [NREL/REopt-API-Analysis#5]
Hi, In the API, what is the profile for the utility charging battery [kw]?
From the webtool, we do have a profile showing how much power is applied from the utility to charge the battery. 

![image](https://user-images.githubusercontent.com/9369525/89728866-351c3280-d9e5-11ea-881e-c54ce8d0d910.png)

**Comment by NLaws** [comment]
@tingm417  The output series you are looking for is in `outputs.Scenario.Site.ElectricTariff. year_one_to_battery_series_kw`. You can find a detailed description and other outputs in the documentation at https://developer.nrel.gov/docs/energy-optimization/reopt-v1/
