### ISSUE TITLE
Where can I find the new V3 "flattened" JSON structure?

### ISSUE THREAD

**Issue by hubert-associates** [NREL/REopt-API-Analysis#68]
Analysis API:
https://github.com/NREL/REopt-API-Analysis/wiki/v3-job-input-and-output-changes

Hi, I need the new V3 "flattened" JSON structure to simplify my mapping to C#.

Saw all the infos, but I can't figure out where the Site data went? latitude,
longitude are "gone". I looked in GitHub branch "develop" but does not seem to
be the V3 json structure. Any pointers greatly appreciated!

Thanks!
Richard

... anything like this great example but using the v3 structure? 
https://github.com/NREL/REopt-API-Analysis/blob/master/single_scenario_example.ipynb

**Comment by hubert-associates** [comment]
Found this, which seems to provide the parts/example I was looking for. https://github.com/NREL/REopt-API-Analysis/blob/master/single_scenario_example.ipynb

**Comment by adfarth** [comment]
Hi Richard, you can find examples of the v3 "flattened" structure are REopt.jl/test/scenarios [linked here](https://github.com/NREL/REopt.jl/tree/master/test/scenarios). In the future, we will update REopt-API-Analysis with a Jupyter Notebook compatible with v3! For future questions, feel free to use the "Discussions" section of this repo :)
